Feature/spell list
brimatteng/Pathfinder-Companion pull request #2
Opened 2017-07-25 22:29 UTC by davidneto92

Spell model created to store vital spell information such as description, school, components, range, duration, and a json/hash structure to store level requirements.

Although the values within the level requirements attribute can be accessed, I am not sure of the best way to filter the spells based on the store values.

2017-07-26 00:41 UTC, brian-penguin requested changes
This looks pretty good dude, Just some small shit

2017-07-26 00:41 UTC, brimatteng commented on db/seeds.rb
> +  return value if value != "NULL" else nil
This is kind of tricky to read. I prefer the multi-line 
```ruby
if value != "NULL"
  value
end
```
It should return nil by default

2017-07-26 00:41 UTC, brimatteng commented on db/seeds.rb
> +  return true if value == 1 else false
Same thing as below

2017-07-26 00:41 UTC, brimatteng commented on db/schema.rb
> +    t.boolean "verbal", default: false
I almost feel `spell_requirements` could be something like `[:verbal, :somatic, :focus]` and those are the actual physical/preparations for the spell

2017-07-26 00:41 UTC, brimatteng commented on db/schema.rb
> +    t.jsonb "spell_requirements"
These are more `class_requirements` than `spell_requirements` I think

2017-07-26 00:41 UTC, brimatteng commented on Gemfile
> +  gem 'pry-rails'
Was Pry not working for you? `pry-byebug` gem should load pry with the ability to step through method calls and what not

2017-07-26 00:41 UTC, brimatteng commented on spec/models/spell_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
I would add just one spec that tests that you can intantiate a model and expect that it responds to methods 

see: https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/respond-to-matcher

2017-07-26 13:40 UTC, davidneto92 commented on db/seeds.rb
> +  return true if value == 1 else false
Done

2017-07-26 13:41 UTC, davidneto92 commented on db/seeds.rb
> +  return value if value != "NULL" else nil
Changed it, I originally had the multi line syntax.

2017-07-26 14:50 UTC, davidneto92 commented on Gemfile
> +  gem 'pry-rails'
No problems with using `binding.pry`. That gem simply makes the rails console use pry instead of IRB. Entirely for creature comfort.

2017-07-26 14:50 UTC, davidneto92 commented on db/schema.rb
> +    t.jsonb "spell_requirements"
That makes sense, corrected.

2017-07-26 14:50 UTC, davidneto92 commented on db/schema.rb
> +    t.boolean "verbal", default: false
So would you rather have the components lumped together into a hash as well?

2017-07-26 14:50 UTC, davidneto92 commented
Corrections made based on comments.

2017-08-04 18:09 UTC, brimatteng commented on db/seeds.rb
> +    class_requirements: build_class_requirements(spell)
This could be an array of class types

2017-08-04 18:10 UTC, brimatteng commented on db/seeds.rb
> +    class_requirements: build_class_requirements(spell)
ie: ['ranger', 'druid']

2017-08-04 18:27 UTC, davidneto92 commented on db/seeds.rb
> +    class_requirements: build_class_requirements(spell)
I don't know if that makes sense, because a spell can be learned at different levels, as in, a sorcerer gets it at 4 and a wizard gets it at 5.

2017-08-04 18:28 UTC, brimatteng commented on db/seeds.rb
> +    class_requirements: build_class_requirements(spell)
yep. ignore this

2017-08-05 00:32 UTC, davidneto92 commented
Added validations to model, added descriptor field (string with "mind", "fear, acid" etc), and small test to validate object creation.

2017-08-05 00:57 UTC, brimatteng commented on app/models/spell.rb
> +  SCHOOLS = [
you can do this with a sigil 
```
%w(abjuration conjuration ...).freeze
```

2017-08-05 01:30 UTC, davidneto92 commented on app/models/spell.rb
> +  SCHOOLS = [
Is that a better practice for the list of schools? It's not like any more will be added (in the near future).

2017-08-07 13:56 UTC, brimatteng commented
Did you figure out the errors with the validations?

2017-08-07 17:33 UTC, davidneto92 commented
I added a few more validations. There are some field I do not know how/if I can add validations to, because the CSV is missing values for those attributes. So it could skip anywhere from 30-400 spells.

2017-08-07 20:05 UTC, brimatteng commented
I think you can have validations and allow null fields as well. That could solve our problems unless there are spelling mistakes

2017-08-08 00:39 UTC, merged